prgkey1 type:xml
prgkey1 value:"http://$$PROXYURL$$:22222/Logon"
prgkey1 states:idle
prgkey1 line:1
prgkey1 locked:0
prgkey2 type:speeddial
prgkey2 value:"*32#"
prgkey2 locked:0
prgkey3 type:xml
prgkey3 value:"http://%ULRSERVER%:22222/Diversion?user=$$SIPUSERNAME$$"
prgkey3 locked:0
prgkey4 type:none
prgkey4 locked:0
prgkey5 locked:1
prgkey6 locked:1
prgkey7 type:directory
prgkey7 locked:1
prgkey8 type:services
prgkey8 locked:1
audio mode:2
