topsoftkey1 type:xml
topsoftkey1 label:"Diversion"
topsoftkey1 value:"http://%ULRSERVER%:22222/Diversion?user=$$SIPUSERNAME$$"
topsoftkey1 locked:0
topsoftkey2 type:none
topsoftkey2 locked:0
topsoftkey3 type:none
topsoftkey3 locked:0
topsoftkey4 type:none
topsoftkey4 locked:0
topsoftkey5 type:none
topsoftkey5 locked:0
topsoftkey6 type:none
topsoftkey6 locked:0
topsoftkey7 type:none
topsoftkey7 locked:0
topsoftkey8 type:none
topsoftkey8 locked:0
topsoftkey9 type:none
topsoftkey9 locked:0
topsoftkey10 type:none
topsoftkey10 locked:0
topsoftkey11 type:none
topsoftkey11 locked:0
topsoftkey12 type:none
topsoftkey12 locked:0
topsoftkey13 type:none
topsoftkey13 locked:0
topsoftkey14 type:none
topsoftkey14 locked:0
topsoftkey15 type:none
topsoftkey15 locked:0
topsoftkey16 type:none
topsoftkey16 locked:0
topsoftkey17 type:none
topsoftkey17 locked:0
topsoftkey18 type:none
topsoftkey18 locked:0
topsoftkey19 type:none
topsoftkey19 locked:0
topsoftkey20 type:none
topsoftkey20 locked:0
collapsed softkey screen:0
collapsed softkey screen offset top:0
softkey1 type:none
softkey1 locked:0
softkey2 type:none
softkey2 locked:0
softkey3 type:none
softkey3 locked:0
softkey4 type:none
softkey4 locked:0
softkey5 type:none
#softkey5 label:"LogOn"
#softkey5 value:"http://$$PROXYURL$$:22222/Logon"
softkey5 states:idle
softkey5 line:1
softkey5 locked:0
softkey6 type:directory
softkey6 locked:0
softkey7 type:none
softkey7 locked:0
softkey8 type:none
softkey8 locked:0
softkey9 type:none
softkey9 locked:0
softkey10 type:none
softkey10 locked:0
softkey11 type:none
softkey11 locked:0
softkey12 type:none
softkey12 locked:0
softkey13 type:none
softkey13 locked:0
softkey14 type:none
softkey14 locked:0
softkey15 type:none
softkey15 locked:0
softkey16 type:none
softkey16 locked:0
softkey17 type:none
softkey17 locked:0
softkey18 type:none
softkey18 locked:0
collapsed softkey screen offset bottom:9
idle screen mode:1
audio mode:2
screen saver background image: http://{{ variables.http_prov_server }}:{{ http_prov_server_port}}/screen_320_240.jpg

