topsoftkey1 type:xml
topsoftkey1 label:"Diversion"
topsoftkey1 value:"http://%ULRSERVER%:22222/Diversion?user=$$SIPUSERNAME$$"
topsoftkey1 locked:0
topsoftkey2 type:none
topsoftkey2 locked:0
topsoftkey3 type:none
topsoftkey3 locked:0
topsoftkey4 type:none
topsoftkey4 locked:0
topsoftkey5 type:none
topsoftkey5 locked:0
topsoftkey6 type:none
topsoftkey6 locked:0
topsoftkey7 type:none
topsoftkey7 locked:0
topsoftkey8 type:none
topsoftkey8 locked:0
topsoftkey9 type:none
topsoftkey9 locked:0
topsoftkey10 type:none
topsoftkey10 locked:0
topsoftkey11 type:none
topsoftkey11 locked:0
topsoftkey12 type:none
topsoftkey12 locked:0
topsoftkey13 type:none
topsoftkey13 locked:0
topsoftkey14 type:none
topsoftkey14 locked:0
topsoftkey15 type:none
topsoftkey15 locked:0
topsoftkey16 type:none
topsoftkey16 locked:0
topsoftkey17 type:none
topsoftkey17 locked:0
topsoftkey18 type:none
topsoftkey18 locked:0
topsoftkey19 type:none
topsoftkey19 locked:0
topsoftkey20 type:none
topsoftkey20 locked:0
topsoftkey21 type:none
topsoftkey21 locked:0
topsoftkey22 type:none
topsoftkey22 locked:0
topsoftkey23 type:none
topsoftkey23 locked:0
topsoftkey24 type:none
topsoftkey24 locked:0
topsoftkey25 type:none
topsoftkey25 locked:0
topsoftkey26 type:none
topsoftkey26 locked:0
topsoftkey27 type:none
topsoftkey27 locked:0
topsoftkey28 type:none
topsoftkey28 locked:0
topsoftkey29 type:none
topsoftkey29 locked:0
topsoftkey30 type:none
topsoftkey30 locked:0
topsoftkey31 type:none
topsoftkey31 locked:0
topsoftkey32 type:none
topsoftkey32 locked:0
topsoftkey33 type:none
topsoftkey33 locked:0
topsoftkey34 type:none
topsoftkey34 locked:0
topsoftkey35 type:none
topsoftkey35 locked:0
topsoftkey36 type:none
topsoftkey36 locked:0
topsoftkey37 type:none
topsoftkey37 locked:0
topsoftkey38 type:none
topsoftkey38 locked:0
topsoftkey39 type:none
topsoftkey39 locked:0
topsoftkey40 type:none
topsoftkey40 locked:0
topsoftkey41 type:none
topsoftkey41 locked:0
topsoftkey42 type:none
topsoftkey42 locked:0
topsoftkey43 type:none
topsoftkey43 locked:0
topsoftkey44 type:none
topsoftkey44 locked:0
collapsed softkey screen:0
collapsed softkey screen offset top:0
softkey1 type:none
softkey1 locked:0
softkey2 type:none
softkey2 locked:0
softkey3 type:none
softkey3 locked:0
softkey4 type:none
softkey4 locked:0
softkey5 type:xml
softkey5 label:"LogOn"
softkey5 value:"http://$$PROXYURL$$:22222/Logon"
softkey5 states:idle
softkey5 line:1
softkey5 locked:0
softkey6 type:none
softkey6 locked:0
softkey7 type:none
softkey7 locked:0
softkey8 type:none
softkey8 locked:0
softkey9 type:none
softkey9 locked:0
softkey10 type:none
softkey10 locked:0
softkey11 type:none
softkey11 locked:0
softkey12 type:none
softkey12 locked:0
softkey13 type:none
softkey13 locked:0
softkey14 type:none
softkey14 locked:0
softkey15 type:none
softkey15 locked:0
softkey16 type:none
softkey16 locked:0
softkey17 type:none
softkey17 locked:0
softkey18 type:none
softkey18 locked:0
softkey19 type:none
softkey19 locked:0
softkey20 type:none
softkey20 locked:0
softkey21 type:none
softkey21 locked:0
softkey22 type:none
softkey22 locked:0
softkey23 type:none
softkey23 locked:0
softkey24 type:none
softkey24 locked:0
collapsed softkey screen offset bottom:9
idle screen mode:1
audio mode:2
screen saver background image: http://{{ variables.http_prov_server }}:{{ http_prov_server_port}}/screen_480_272.jpg
