# Mitel/Aastra Configuration File
# Generated by Provisioning System for domain: {{ domain_name }}

# Aastra 67xxi Configuration File (MX-ONE 4.1 SP2 HF2)
# ================================================================
# Verified Terminal 67xxi-FW: 3.2.2
# companion configuration template: 00XXXXXXXXXX.cfg.template (<mac>.cfg)
#
# Manager Telephony System (TS) uses the configuration options in this file as default.
# For most deployments, configuring the terminals via Manager TS would be sufficient
#
# This file must be renamed to "aastra.cfg"
# The "aastra.cfg" file configures the settings server wide, while
# the "<mac>.cfg" file configures only the phone with the MAC address
# for which the file is named (for example, "00085d0304f4.cfg"). The
# settings in the "aastra.cfg" file will be overridden by settings
# which also appear in the "<mac>.cfg" file.
#
# "active" options,ie not listed as comment, "#", is a working example
# together with the companion template <mac>.cfg file (and its active options).
# There are alternative suggestions for deployment described as well
# which does not require <mac>.cfg
#
# How to maintain the terminals:
# MX-ONE Library, MX-ONE Telephony System/Installation:
# - The general Administrators Guide, "9143i, 9480i, 9480i CT and 67xxi, Administrator Guide, Release 2.6"
# - Aastra 67xxi (Installation Instruction). This document describes the installation on MX-ONE
# Download FW from Service Plaza or go to
# http://www.aastra.com/document-library.htm
# => On Desk Phones, click on "Learn more"
# => Click on for example '6750i' for the Aastra 675xi series.
# => Click on a model in the list, for example 6757i
# => FW: Downloads->Software Releases. The latest FW is listed on top
#
# QUICK GUIDE TO GET THE TELEPHONES UP AND RUNNING
#------------------------------------------------------------------
# 1. Is a vlan used MX-ONE and the terminals?
#    Enable settings at "#VLAN Setting".
# 2. Does DHCP return 'Option 66' with Configuration Server?
#    Skip setting Configuration Server. Go to "4".
# 3. Set Configuration Server
#    Enable settings at "# Configuration Server Settings"
# 4. Set up SIP Server.
#    Configure the "sip proxy ip"
#
#Admin password
#--------------
#Make use of anacrypt.exe to encrypt an aastra.cfg into an encrypted aastra.tuz
#(This also works for <mac>.cfg with an encrypted file stored as <mac>.tuz
#admin password: 22222 # default: 22222, Range: 0..4294967295

#Access via WebUI
#web interface enabled: 1 #Default Enable(1), Disable(0)

#------------------------------------------------------------------
# Network Settings
## = = = = = = = = = = = = = =
dhcp:1          # DHCP enabled
# DHCP:
# 0 = false, means DHCP is disabled.
# 1 = true, means DHCP is enabled.

#rfc4594 defines classes values below
#MX-ONE telephony server specifies Diffserv value in hexadecimal (0x)
#for call_control(signaling) and media during installation.
#Signaling service class (CS5/0b101000 == DSCP 40 (decimal value) => Diffserv 0b10100000 (0xa0)
#MX-ONE Telephony Server (AF43/0b100110 == DSCP 38) => Diffserv 0b10011000 (0x98)
#Here DSCP 38 is used as the default setting in MX-ONE Telephony Server is assumed
tos sip:38 #DSCP 26 (default) [AF31]

#Telephony Server Class (EF/101110) == DSCP 46
#EF is specified for audio over RTP in rfc3246
#tos rtp: 46  #DSCP 46 (default)

#VLAN Setting
#tagging enabled: 1
#VLAN id: 22

#-------------------------------------------------------------------
# Configuration Server Settings
## = = = = = = = = = = = = = = =
# Notes: This section defines which server the phone retrieves new
# firmware images and configuration files from.
# valid values are HTTP, TFTP, FTP and
## HTTP server settings
download protocol:HTTP
http server:{{http_prov_server}}  #can be IP or FQDN
http path:aastra67xxi
http port:80
## TFTP server settings
#tftp server: 10.0.0.1
#tftp path: aastra67xxi
#alternate tftp server:
#alternate tftp path: aastra67xxi
#use alternate tftp server: 1  # If your DHCP server assigns
                               # a TFTP server address which
                               # you do not use, you can use
                               # the alternate tftp server.
## FTP server settings
#ftp server: 192.168.0.131  #can be IP or FQDN
#tfp path: aastra67xxi
#ftp username:
#ftp password:




#-------------------------------------------------------------------
# Dial Plan Settings
# =====================
#
emergency dial plan:112|11414 # numbers allowed to dial when phone is locked

!sip dial plan:"x+^|xx+*|1xxx"     #MUST
!sip dial plan terminator:"1"   #MUST, enable(1), disable(0) using hash to dial(presently required to send trailing hash)

sip digit timeout:3      # set the inter-digit timeout in seconds

# Time Server Settings
## =====================
time server disabled:0    #server enabled(0), server disabled(1)
#dst config: 3             #daylight savings, OFF(0), 30 min summertime(1), 1h summertime(2), automatic(3)(default)

time server1:{{ ntp_server }}
time server2:ru.pool.ntp.org
#time server2: # least one time server IP address or
#time server3: # qualified domain name

#Time and Date Settings
## ====================
time zone name:EU-Moscow #SE-Stockholm  #Required setting if time-server is enabled
time format:1 #12hours(0), 24hours(1)
date format:2 #YYYY-MM-DD(2)

# Language
##===============
#Aastra Web UI and Phone UI language.

#Maximum of 4 language files can be loaded to the terminals.
#The language packs, lang_<..>.txt, are distributed in a separate LangPacks_<version>.zip from
#the phone firmware download area at Service Plaza or http://www.aastratelecom.com/.
#The (Customer Service Unit)CSU might have more languages to offer.
#A language files can be created using the naming convention of ISO639 and ISO3166 described in the IP-Admin guide.

#language [1..4]: lang_<ISO639-1_language-code>[_<ISO3166-1_country-code>].txt
#LangPacks_2.6.zip: lang_de.txt, lang_es.txt, lang_es_mx.txt, lang_fr.txt
#lang_fr_ca.txt, lang_it.txt, lang_pt.txt, lang_pt_br.txt and lang_ru.txt
#language 1: lang_es.txt       #Spanish
#language 2: lang_pt_br.txt    #Portugese(Brasilian dialect)
#language 3: lang_pt.txt       #Portugese(dialect of Portugal assumed)
#language 4: lang_sv.txt       #Swedish, not part of Canadian distribution of LangPacks.zip, but can be found on Service Plaza

#Default language.
#syntax: language: X; X={0-English, 1..4 matches the language loaded via "language X:  lang_<..>}
#language: 0     # set default Phone UI (Default:0 is English)
#web language: 0 # set default Web UI

#Character input (virtual keyboard on Aastra 6739i)
#input language: Nordic   #Range: English,French,German,Italian,Spanish,Portuguese,Russian,Nordic Default:English

#------------------------------------------------------------------
# Tone set
#=================

tone set:Europe
#[set your market: Australia, Europe (generic tones),France,Germany,Italy,Mexico,Brazil,United Kingdom,US]
# MX-ONE will send Alert-Type with bellcore definition for
# the below bellcore definitions. These are matched to external cadence and callback cadence
# in /etc/opt/eri_sn/ip_telephony.conf
# external call cadence
bellcore cadence dr2:350,300,350,5000
# callback cadence
bellcore cadence dr3:300,400

#------------------------------------------------------------------
# General SIP Settings
# = = = = = = = = = = =
sip session timer:1800 # (second), enable support of RFC4028, the default(0) disables the function
sip transport protocol:1 # use UDP (1), TCP (2), both SIP and UDP (0), TLS(4) for sip
#sip use basic codecs: 1 #Basic codecs are limited to (1)G.711u(PCMU), (2)G.711a(PCMA), (3)G729
#sip silence suppression: 1  # 1(enabled),silence suppression is enabled by default ie G.711 with CN(rfc3389) or G.729ab
#Instead of setting "sip use basic codecs" and "sip silence suppression". "sip customized codec" can be used to get the wanted behaviour
#Set codec priority to (1) G.722, (2) G.711a(PCMA), (3) G.711u(PCMU), (4) G.729 --> Priority set to use G.722 wideband for improve audio performance
sip customized codec:payload=9;ptime=20;silsupp=off,payload=8;ptime=20;silsupp=off,payload=0;ptime=20;silsupp=off,payload=18;ptime=20;silsupp=off
sip silence suppression:0 # silence suppression: deactivated (0), activated (1)


#sip out-of-band dtmf: 1 #turn off support for RFC2833 (on by default)
#sip dtmf method: 0      #0(RTP), 1(SIP INFO), 2(BOTH)
#

sip out-of-band dtmf:1 #RFC2833 enabled (1), requires sip dtmf method: 0 (RTP) to be effective
sip dtmf method:1      #0(RTP), 1(SIP INFO), 2(BOTH)
sip line1 dtmf method:1      #0(RTP), 1(SIP INFO), 2(BOTH)
sip line2 dtmf method:1      #0(RTP), 1(SIP INFO), 2(BOTH)

sip srtp mode:0        #0(SRTP disabled),1(SRTP preferred),2(SRTP only)

#If TLS shall be used, the certificates and outbound proxy must be set. MX-ONE listens for TLS on port:5061
#sips persistent tls: 1
#sip outbound support: 1
#sip transport protocol: 4 # use UDP (1), TCP (2), both SIP and UDP (0, TLS(4) for sip messaging
#sips trusted certificates: "trustedCert.pem" //read from Configuration Server
#sip outbound proxy: 10.105.20.31
#sip outbound proxy port:5061
#sip srtp mode: 1                 #0(SRTP disabled),1(SRTP preferred),2(SRTP only)

#-------------------------------------------------------------------
# When HTTPS used for in XML keys to MX-ONE telephony Server
#-------------------------------------------------------------------

https client method:"TLS 1.0"
https redirect http get:0  #only use https if explicitly set in the xml key value
https validate certificates:0  #MUST be set to 0 if the phone shall accept the certificate set below
#https user certificates: "trustedCert.pem"  //read from Configuration Server


# Per-line SIP Settings ( <mac>.cfg configuration unless free-seating is used (see further down)
# ======================

# Advanced SIP Settings
# ======================

sip vmail:67777   #number to voice mail.
                   #For OneBox, use the GH number. For Exchange Server use the trunk dest number.
sip line1 vmail:67777
#The vmmail number is dialled if "voice mail" is selected in "Services" function key.
sip explicit mwi subscription:1
sip explicit mwi subscription period:1800
#MWI subscription (Message Waiting Indication)
#Feature desc:A mail icon is displayed if the user has a voice mail on external Voice Mail server.
#Prereq: This requires that OneBox or another VoiceMail server is integrated with MX-ONE
auto resync mode:3     #The terminal will check for new FW or configuration (aastra.cfg/mac.cfg) every day..
auto resync time:03:00 #at the time specified OR when the terminal has made a reboot/reset
auto resync max delay:60 #Range:0..1439 minutes. default:15. The maximum time the phone waits past the scheduled time before starting a checksync



#------------------------------------------------------------------
# MX-ONE features
#
# All Aastra 67xxi supports aastra-xml for configuration
#1. Common features
#- free seating via Logon and Logoff softkeys. Note the label for these keys are set in this file and can be set in your language.
#- free-seating via Feature Code {LOGON: *11*<password>*<extension>#, *11*<extension>#; LOGOFF: #11#}
#  free-seating works as for DBC terminals, i.e the previous terminal is automatically logged out when the user logon to the present terminal.
#- Display of own extension and name. NIINI is input for name. MX-ONE configures these via
#  sip screen name <=> "#<profile number> <extension>", example "#1 67555",
# (i.e profile number set via *10*<profile nr># or PEN key; extension set via *11* , logon key or '"sip user name" via <mac>.cfg')
#  sip screen name 2 <=> NIINI (name1 and name2), "<name1> <name2>", example "Per Persson"
#  Note, do not set "sip screen name" or "sip screen name 2" via <mac>.cfg it will be overwritten by MX-ONE configuration
#- Name identification for called party in alerting
#- Phone status for Message Diversion (ie absence reason for ex "Gone Home")(activate via *23*0# (Lunch) etc, remove via #23#)
#- In a call to extension that has activated Message Diversion, the display will show (for example "Gone Home"),
#  the call will be directed to "Direct Diversion" answering position (for example operator, 09)
#- Phone status on for Follow-Me (activate via *21*<follow-me-to-number>#, remove via #21#)
#- Busy Services triggered via digits (Intrusion(4), Call-Waiting(5), Call-back(6) and Call-pickup(8))
#  The values is dependent on market. These values are applicable for market 'standard'
#  Note, call-waiting is a service only available towards h.323 and DTS
#- Message Waiting Indication (no configuration needed in MX-ONE, only configuration enabled by default in this file is required)
#
#- MX-ONE function keys MNS,TNS and MCT (not 6751i):
#  In MX-ONE extension_key --function {MNS|TNS|MCT|PEN} -d <extension nr> --key, the
#  --key N maps to ExpMod1SoftKeyN if expansion module is available, otherwise prgkeyX, topsoftkeyX or softkeyX
#  according to /etc/opt/eri_sn/ip_telephony.conf on MX-ONE Telephony Server
#
#  Boss's PEN: extension_key -d <Boss extension nr> --key <> --function PEN --key-on-call-list X --key-off-call-list Y
#  Secretary's PEN: extension_key -d <Secretary's extension nr> --key <> --function PEN --monitored-dir <Boss extension nr> --key-on-call-list X --key-off-call-list Y
#  PEN key is activated => call list profile #X is set according to --key-on-call-list X
#  PEN key is deactivated => call list profile #Y is set according to --key-off-call-list Y
#  Call list profile is set via command call_list
#
#  These MX-ONE function keys will be realized using built-in types on the Aastra67xxi terminals:
#  blf(busy line feed) <=> MNS
#  blf will have one ring signal (equivalent to extension_key --alert-type 3)
#  if "play a ring splash" is enabled
play a ring splash:1   #0(disabled)[default], 1(enabled)
#  speeddial <=> TNS
#  NOTE: blf will only work if set via MX-ONE command, extension_key.
#
#2. Features only supported by 6755i,6757i and 6739i. These have a main soft display, controlled via softkeys and input screens
# has the following extra features:
#- In a call to extension that has activated Message Diversion, the display will show (for example "Gone Home")
#  and the user can press softkey "Dial" to immediately call "Direct Diversion" answering position (for example operator, 09)
#- Busy Services (Call-back, Intrusion, Call-pickup and ) via softkeys
#- Call-back at no answer via softkeys
# Note, Busy Services and 'Call-back at no answer' will only be
# visible when the "More" button is pressed on 6755i and 6757i terminals.
#
#------------------------------------------------------------------
#
#These settings are required to support the extra features above
!sip aastra id:1
!sip send line:1
!sip xml notify event:1
!sip pai:1
!directed call pickup:1
!directed call pickup prefix: Pickup
!collapsed context user softkey screen:1

#disable local  'conf' to promote central conference with 3 parties using DTMF '3'
#conference hard key on Aastra 673xi is mapped to send DTMF 3
conference disabled:1
map conf as dtmf:1
map conf key to:3

#disable local call forwarding to promote
#1. *21*, *22# or menu MX-ONE menu Diversion.
#2. call_list (Personal Number)
call forward disabled:1
#'speeddial edit' enables/disables the press-and-hold speedial edit feature. This feature is disabled per default in MX-ONE.
#The reason is that for softkeys, the first available key is always configured which is the reserved key softkey1, set to type: none, below
speeddial edit:"0" #default enabled(1),disabled(0)


dynamic sip:1
sip line1 user name:"NotConfigured"    #A user name must be set to enable *11* and SOS calls
sip proxy ip:{{ sip_server_ip }}
sip proxy port:{{ sip_server_port }}
sip registrar ip:{{ sip_server_ip }}
sip registrar port:5060

#Backup registrar and proxy may be set for Redundancy
#sip backup proxy ip: 192.168.20.32
#sip backup proxy port: 5060
#sip backup registrar ip: 192.168.20.32
#sip backup registrar port: 5060

softkey5 label:"LogOn"
softkey5 type:xml
softkey5 value:http://$$PROXYURL$$:22222/Logon
softkey5 states:idle
softkey5 line:1

action uri startup:http://$$PROXYURL$$:22222/Logon?user=$$SIPUSERNAME$$


#------------------------------------------------------------------
# Key configuration
#
# Consider teaching the end-user to set softkeys or prgkey keys using
# using the web-GUI to the terminal using username "user"
# and no password(left blank)
# Note that blf will only work via command (see MX-ONE offers.. above)
#
# Programmable keys
#    6753i,6755i: prgkey1 - prgkey6
#    6730,6731: prgkey1 - prgkey8
#
# Soft keys
#    6757i,6757i CT: topsoftkey1 - topsoftkey10
#    6755i,6757i, and 6757i CT: softkey1 - softkey20
#    6739i - softkey1-softkey55
#
#    1-3 expansion modules (N=1-3)
#    ExpModNSoftKey1 - ExpModNSoftKey60
#
#    softkeyN/topsoftkeyN/prgkeyN type:
#    softkeyN/topsoftkeyN label:
#    softkeyN/topsoftkeyN/prgkeyN value:
#    softkeyN/topsoftkeyN/prgkeyN line:
#    softkeyN states:
#    softkeyN/topsoftkeyN/prgkeyN locked:
#
#softkey 1-4 are used by MX-ONE for Busy Services.
#Any configuration on these keys will be overwritten unless busy services is disabled
#Config in /etc/opt/eri_sn/ip_telephony.conf
#   Disable Busy Services for SIP. Forces SIPLP to respond with 486 Busy
#   Possible values: yes/no
#   Default value: no
#System:Default:SIP:DisableBusyServices: no
softkey1 value:none
softkey2 value:none
softkey3 value:none
softkey4 value:none

#6755i,6757i,5739i (softkey terminal settings)

#Corporate Directory, based on XML-kit directory_ldap.zip, is supported in CMG 7.5 SP1
#All terminals are supported
#softkey6 label: "CorpDir"
#softkey6 type: xml
#softkey6 value:  http://<CMG server>/xml/directory/CorpDir.php
#softkey6 line: global
#softkey6 states: idle, connected, incoming, outgoing

#softkey7 label: "MsgWaiting"  #retrieving messages from Voice Mail, operators or other users
#softkey7 type: speeddial
#softkey7 value: "*32#"
#softkey7 line: global
#softkey7 states: idle

#softkey8 label: ""
#softkey8 type: xml
#softkey8 value: http://$$PROXYURL$$:22222/??
#softkey8 states: idle, connected, incoming, outgoing
#softkey8 line: global

# 6753i, keys 1,2 are reserved for SAVE and DELETE in factory default configuration
# 6730i, 6731i, keys 5,6 are reserved for SAVE and DELETE in factory default configuration
# SAVE and DELETE can not be configured via configuration file as a type of key.
# SAVE and DELETE are needed to handle 'Callers List', Directory and save
# prgkey{1,2,5,6} locked: 0 will make it possible to configure other types,
# but will keep SAVE and DELETE as default keys on these terminals

#Default setting in MX-ONE ip_telephony.conf:
#Aastra 6753 has no individual keys (set via MX-ONE command, extension_key --function {MNS|TNS|MCT|PEN})
#Aastra 6730,6731 is open for individual keys on prgkey1..4.
#The Quick Ref Guide refers to settings on prgkey 7..8 on these terminals.
#It is possible to protect these keys with suffix "!"

#6753i and 6730i,6731i factory default configuration is preserved
prgkey1 locked:0
prgkey2 locked:0
prgkey3 locked:0
prgkey4 type:callers   #This will override Icom on 6755i and is default setting for 6753i
prgkey5 locked:0
prgkey6 locked:0
#6730i,6731i is enabled for extension_key on key 1..4. So, the common keys are set on prgkey7..8
prgkey7 type:directory
#key8:"VoiceMail"
prgkey8 type:speeddial
prgkey8 value:"67777"

#6757i
topsoftkey1 label:"VoiceMail"
topsoftkey1 type:speeddial
topsoftkey1 value:"67777"  #same as "sip vmail:" which is mapped to a fixed key on 6739i
topsoftkey2 label:"LocalDir"
topsoftkey2 type:directory
topsoftkey3 label:"CallList"
topsoftkey3 value:callers
topsoftkey4 label:"MsgWaiting"  #retrieving messages from Voice Mail, operators or other users
topsoftkey4 type:speeddial
topsoftkey4 value:"*32#"

#Types listed for softkeys in WebUI or PhoneUI
softkey selection list: "none,speeddial,line,xml,speeddialxfer,speeddialconf,dnd,services,phonelock,empty"
